FROM golang:1.23 AS build

ENV PATH="$PATH:$(go env GOPATH)/bin"

COPY go.mod go.sum /src/
COPY frontend /src/frontend

ENV CGO_ENABLED=0
RUN cd /src && go build -o /frontend frontend/main.go

FROM alpine:3.20

COPY --from=build /frontend /frontend
COPY --from=build /src/frontend/templates /templates
COPY frontend/config.yaml /config.yaml

ENTRYPOINT [ "/frontend" ]